[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["cd backend && python3 -m pip install -r requirements.txt"]

[start]
cmd = "cd backend && python3 -m gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
